import type { Freq } from "./recurrence";

/**
 * Quick-add vocabulary, one lexicon per UI language. `quickAddParse` matches the UI language's
 * lexicon first and English after it, so English phrases work in every language. Every phrase is
 * lowercase and space-separated, and is matched accent-insensitively ({@link fold}), so "manana",
 * "lunedi" and "uebermorgen" work as well as the proper spelling.
 */
export interface QuickAddLexicon {
  /** Month before day ("jun 3") as well as day before month ("3 jun"). */
  monthFirst?: boolean;
  /** Words for a count of one: "in a week", "om en uge". */
  one: string[];
  /** A unit straight after an `inPrefixes` word means one of it: Polish "za tydzień". */
  inBareUnit?: boolean;
  /** Time prefixes that may be glued to the hour: Danish "kl17", "kl.9:30". */
  gluedTimePrefixes?: string[];
  /** Phrases that name a day relative to today: "morgen" → 1. */
  relativeDays: Record<string, number>;
  /** Weekday names and their inflected/plural forms, Sunday = 0. */
  weekdays: Record<string, number>;
  /** Month names (and the genitive forms dates use), January = 0. */
  months: Record<string, number>;
  /** Day/week/month/year in every form a count can take. */
  units: Record<string, Freq>;
  /** Before a count and unit: "in 3 Tagen" → "in". */
  inPrefixes: string[];
  /** Before a weekday or unit: "nächsten Montag". */
  nextPrefixes: string[];
  /** After a weekday or unit: "lundi prochain". */
  nextSuffixes: string[];
  /** Before a weekday: "diesen Freitag". */
  thisPrefixes: string[];
  /**
   * Words consumed in front of a date only when the date follows: "am Montag", "el lunes",
   * "w środę", "la semaine prochaine". Never matched on their own.
   */
  leadIns: string[];
  /** Between a day number and its month: "3 de marzo". */
  monthConnectors: string[];
  /** Before a weekday, a unit, or a count and unit: "jede Woche", "alle 2 Wochen". */
  every: string[];
  /** One word or phrase that is a whole rule: "täglich" → daily. */
  single: Record<string, Freq>;
  /** After a rule: schedule from the completion date, like `every!`. */
  fromCompletion: string[];
  /**
   * Before a time. `true` accepts a bare hour ("um 17"); `false` needs minutes ("o 17:30"), for a
   * prefix that is also an everyday word.
   */
  timePrefixes: Record<string, boolean>;
  /** A word after the hour: "17 Uhr". */
  timeSuffixes: string[];
  /** Letter glued to the hour: "17h30" (French), "17u" (Dutch). */
  hourLetter?: string;
  noon: string[];
  midnight: string[];
}

/** Lowercase, strip accents and unify apostrophes, for accent-insensitive matching. */
export function fold(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/ł/g, "l")
    .replace(/ß/g, "ss")
    .replace(/[’‘`]/g, "'");
}

const DE: QuickAddLexicon = {
  one: ["einer", "einem", "einen", "eine"],
  relativeDays: {
    heute: 0,
    "heute abend": 0,
    "heute morgen": 0,
    "heute früh": 0,
    morgen: 1,
    übermorgen: 2,
    uebermorgen: 2,
  },
  weekdays: {
    sonntag: 0,
    montag: 1,
    dienstag: 2,
    mittwoch: 3,
    donnerstag: 4,
    freitag: 5,
    samstag: 6,
    sonnabend: 6,
    sonntags: 0,
    montags: 1,
    dienstags: 2,
    mittwochs: 3,
    donnerstags: 4,
    freitags: 5,
    samstags: 6,
  },
  months: {
    januar: 0,
    jänner: 0,
    februar: 1,
    märz: 2,
    maerz: 2,
    april: 3,
    mai: 4,
    juni: 5,
    juli: 6,
    august: 7,
    september: 8,
    oktober: 9,
    november: 10,
    dezember: 11,
    jan: 0,
    feb: 1,
    mär: 2,
    apr: 3,
    jun: 5,
    jul: 6,
    aug: 7,
    sep: 8,
    sept: 8,
    okt: 9,
    nov: 10,
    dez: 11,
  },
  units: {
    tag: "daily",
    tage: "daily",
    tagen: "daily",
    woche: "weekly",
    wochen: "weekly",
    monat: "monthly",
    monate: "monthly",
    monaten: "monthly",
    jahr: "yearly",
    jahre: "yearly",
    jahren: "yearly",
  },
  inPrefixes: ["in"],
  nextPrefixes: ["nächsten", "nächste", "nächster", "nächstes", "kommenden", "kommende"],
  nextSuffixes: [],
  thisPrefixes: ["diesen", "diese", "dieses"],
  leadIns: ["am"],
  monthConnectors: [],
  every: ["jeden", "jede", "jedes", "alle"],
  single: { täglich: "daily", wöchentlich: "weekly", monatlich: "monthly", jährlich: "yearly" },
  fromCompletion: ["nach erledigung", "ab erledigung"],
  timePrefixes: { um: true },
  timeSuffixes: ["uhr"],
  noon: ["mittag", "mittags"],
  midnight: ["mitternacht"],
};

const ES: QuickAddLexicon = {
  one: ["un", "una"],
  relativeDays: {
    hoy: 0,
    "esta noche": 0,
    "esta tarde": 0,
    mañana: 1,
    "pasado mañana": 2,
  },
  weekdays: {
    domingo: 0,
    lunes: 1,
    martes: 2,
    miércoles: 3,
    jueves: 4,
    viernes: 5,
    sábado: 6,
    domingos: 0,
    sábados: 6,
  },
  months: {
    enero: 0,
    febrero: 1,
    marzo: 2,
    abril: 3,
    mayo: 4,
    junio: 5,
    julio: 6,
    agosto: 7,
    septiembre: 8,
    setiembre: 8,
    octubre: 9,
    noviembre: 10,
    diciembre: 11,
    ene: 0,
    abr: 3,
    ago: 7,
    dic: 11,
  },
  units: {
    día: "daily",
    días: "daily",
    semana: "weekly",
    semanas: "weekly",
    mes: "monthly",
    meses: "monthly",
    año: "yearly",
    años: "yearly",
  },
  inPrefixes: ["en", "dentro de"],
  nextPrefixes: ["próximo", "próxima"],
  nextSuffixes: ["que viene", "próximo", "próxima"],
  thisPrefixes: ["este", "esta"],
  leadIns: ["el", "la"],
  monthConnectors: ["de"],
  every: ["cada", "todos los", "todas las"],
  single: {
    diariamente: "daily",
    "a diario": "daily",
    semanalmente: "weekly",
    mensualmente: "monthly",
    anualmente: "yearly",
  },
  fromCompletion: ["desde completar", "tras completar", "al completar"],
  timePrefixes: { "a las": true, "a la": true },
  timeSuffixes: ["h"],
  hourLetter: "h",
  noon: ["mediodía"],
  midnight: ["medianoche"],
};

const FR: QuickAddLexicon = {
  one: ["un", "une"],
  relativeDays: {
    "aujourd'hui": 0,
    "ce soir": 0,
    demain: 1,
    "après-demain": 2,
    "après demain": 2,
  },
  weekdays: {
    dimanche: 0,
    lundi: 1,
    mardi: 2,
    mercredi: 3,
    jeudi: 4,
    vendredi: 5,
    samedi: 6,
    dimanches: 0,
    lundis: 1,
    mardis: 2,
    mercredis: 3,
    jeudis: 4,
    vendredis: 5,
    samedis: 6,
  },
  months: {
    janvier: 0,
    février: 1,
    mars: 2,
    avril: 3,
    mai: 4,
    juin: 5,
    juillet: 6,
    août: 7,
    septembre: 8,
    octobre: 9,
    novembre: 10,
    décembre: 11,
    janv: 0,
    févr: 1,
    avr: 3,
    juil: 6,
    sept: 8,
    oct: 9,
    déc: 11,
  },
  units: {
    jour: "daily",
    jours: "daily",
    semaine: "weekly",
    semaines: "weekly",
    mois: "monthly",
    an: "yearly",
    ans: "yearly",
    année: "yearly",
    années: "yearly",
  },
  inPrefixes: ["dans"],
  nextPrefixes: [],
  nextSuffixes: ["prochain", "prochaine"],
  thisPrefixes: ["ce", "cette"],
  leadIns: ["le", "la"],
  monthConnectors: [],
  every: ["chaque", "tous les", "toutes les"],
  single: {
    quotidiennement: "daily",
    hebdomadairement: "weekly",
    mensuellement: "monthly",
    annuellement: "yearly",
  },
  fromCompletion: ["après achèvement", "à partir de la fin"],
  // "à" folds to "a" ("Paul a 17 ans"), so a bare hour needs its "h": "à 17h".
  timePrefixes: { à: false },
  timeSuffixes: ["h"],
  hourLetter: "h",
  noon: ["midi"],
  midnight: ["minuit"],
};

const IT: QuickAddLexicon = {
  one: ["un", "una", "uno"],
  relativeDays: {
    oggi: 0,
    stasera: 0,
    domani: 1,
    dopodomani: 2,
  },
  weekdays: {
    domenica: 0,
    lunedì: 1,
    martedì: 2,
    mercoledì: 3,
    giovedì: 4,
    venerdì: 5,
    sabato: 6,
  },
  months: {
    gennaio: 0,
    febbraio: 1,
    marzo: 2,
    aprile: 3,
    maggio: 4,
    giugno: 5,
    luglio: 6,
    agosto: 7,
    settembre: 8,
    ottobre: 9,
    novembre: 10,
    dicembre: 11,
    gen: 0,
    mag: 4,
    giu: 5,
    lug: 6,
    ago: 7,
    set: 8,
    ott: 9,
    dic: 11,
  },
  units: {
    giorno: "daily",
    giorni: "daily",
    settimana: "weekly",
    settimane: "weekly",
    mese: "monthly",
    mesi: "monthly",
    anno: "yearly",
    anni: "yearly",
  },
  inPrefixes: ["tra", "fra"],
  nextPrefixes: ["prossimo", "prossima"],
  nextSuffixes: ["prossimo", "prossima"],
  thisPrefixes: ["questo", "questa"],
  leadIns: ["il", "la"],
  monthConnectors: [],
  every: ["ogni", "tutti i", "tutte le"],
  single: {
    quotidianamente: "daily",
    giornalmente: "daily",
    settimanalmente: "weekly",
    mensilmente: "monthly",
    annualmente: "yearly",
  },
  fromCompletion: ["dal completamento", "dopo il completamento"],
  timePrefixes: { alle: true, "all'": true, "a mezzogiorno": false },
  timeSuffixes: [],
  noon: ["mezzogiorno"],
  midnight: ["mezzanotte"],
};

const NL: QuickAddLexicon = {
  one: ["een"],
  relativeDays: {
    vandaag: 0,
    vanavond: 0,
    morgen: 1,
    overmorgen: 2,
  },
  weekdays: {
    zondag: 0,
    maandag: 1,
    dinsdag: 2,
    woensdag: 3,
    donderdag: 4,
    vrijdag: 5,
    zaterdag: 6,
  },
  months: {
    januari: 0,
    februari: 1,
    maart: 2,
    april: 3,
    mei: 4,
    juni: 5,
    juli: 6,
    augustus: 7,
    september: 8,
    oktober: 9,
    november: 10,
    december: 11,
    jan: 0,
    feb: 1,
    mrt: 2,
    apr: 3,
    jun: 5,
    jul: 6,
    aug: 7,
    sep: 8,
    sept: 8,
    okt: 9,
    nov: 10,
    dec: 11,
  },
  units: {
    dag: "daily",
    dagen: "daily",
    week: "weekly",
    weken: "weekly",
    maand: "monthly",
    maanden: "monthly",
    jaar: "yearly",
    jaren: "yearly",
  },
  inPrefixes: ["over"],
  nextPrefixes: ["volgende", "komende"],
  nextSuffixes: [],
  thisPrefixes: ["deze"],
  leadIns: ["op"],
  monthConnectors: [],
  every: ["elke", "iedere", "om de"],
  single: { dagelijks: "daily", wekelijks: "weekly", maandelijks: "monthly", jaarlijks: "yearly" },
  fromCompletion: ["na voltooiing", "vanaf voltooiing"],
  timePrefixes: { om: true },
  timeSuffixes: ["uur"],
  hourLetter: "u",
  // "middag" is the afternoon, not noon; "12 uur" covers it.
  noon: [],
  midnight: ["middernacht"],
};

const PL: QuickAddLexicon = {
  inBareUnit: true,
  one: [],
  relativeDays: {
    dziś: 0,
    dzisiaj: 0,
    "dziś wieczorem": 0,
    "dzisiaj wieczorem": 0,
    jutro: 1,
    pojutrze: 2,
  },
  weekdays: {
    niedziela: 0,
    niedzielę: 0,
    niedziele: 0,
    poniedziałek: 1,
    poniedziałki: 1,
    wtorek: 2,
    wtorki: 2,
    środa: 3,
    środę: 3,
    środy: 3,
    czwartek: 4,
    czwartki: 4,
    piątek: 5,
    piątki: 5,
    sobota: 6,
    sobotę: 6,
    soboty: 6,
  },
  months: {
    styczeń: 0,
    stycznia: 0,
    luty: 1,
    lutego: 1,
    marzec: 2,
    marca: 2,
    kwiecień: 3,
    kwietnia: 3,
    maj: 4,
    maja: 4,
    czerwiec: 5,
    czerwca: 5,
    lipiec: 6,
    lipca: 6,
    sierpień: 7,
    sierpnia: 7,
    wrzesień: 8,
    września: 8,
    październik: 9,
    października: 9,
    listopad: 10,
    listopada: 10,
    grudzień: 11,
    grudnia: 11,
    sty: 0,
    lut: 1,
    kwi: 3,
    cze: 5,
    lip: 6,
    sie: 7,
    wrz: 8,
    paź: 9,
    lis: 10,
    gru: 11,
  },
  units: {
    dzień: "daily",
    dni: "daily",
    dnia: "daily",
    tydzień: "weekly",
    tygodnie: "weekly",
    tygodni: "weekly",
    tygodnia: "weekly",
    tygodniu: "weekly",
    miesiąc: "monthly",
    miesiące: "monthly",
    miesięcy: "monthly",
    miesiąca: "monthly",
    miesiącu: "monthly",
    rok: "yearly",
    lata: "yearly",
    lat: "yearly",
    roku: "yearly",
  },
  inPrefixes: ["za"],
  nextPrefixes: [
    "następny",
    "następna",
    "następną",
    "następnym",
    "przyszły",
    "przyszła",
    "przyszłą",
    "przyszłym",
  ],
  nextSuffixes: [],
  thisPrefixes: ["ten", "ta", "tę", "w ten", "w tę"],
  leadIns: ["w", "we"],
  monthConnectors: [],
  every: ["co", "każdy", "każdego", "w każdy", "w każdą", "każdą"],
  single: {
    codziennie: "daily",
    cotygodniowo: "weekly",
    comiesięcznie: "monthly",
    corocznie: "yearly",
  },
  fromCompletion: ["od ukończenia", "od wykonania"],
  // "o" is also "about": "o 2 projektach" must not read as 02:00, so a bare hour needs "godz.".
  timePrefixes: { o: false, "o godz.": true, "o godz": true, "o godzinie": true, "godz.": true },
  timeSuffixes: [],
  noon: ["południe", "w południe"],
  midnight: ["północ", "o północy"],
};

const PT: QuickAddLexicon = {
  one: ["um", "uma"],
  relativeDays: {
    hoje: 0,
    "hoje à noite": 0,
    "esta noite": 0,
    amanhã: 1,
    "depois de amanhã": 2,
  },
  weekdays: {
    domingo: 0,
    "segunda-feira": 1,
    segunda: 1,
    "terça-feira": 2,
    terça: 2,
    "quarta-feira": 3,
    quarta: 3,
    "quinta-feira": 4,
    quinta: 4,
    "sexta-feira": 5,
    sexta: 5,
    sábado: 6,
    domingos: 0,
    segundas: 1,
    terças: 2,
    quartas: 3,
    quintas: 4,
    sextas: 5,
    sábados: 6,
  },
  months: {
    janeiro: 0,
    fevereiro: 1,
    março: 2,
    abril: 3,
    maio: 4,
    junho: 5,
    julho: 6,
    agosto: 7,
    setembro: 8,
    outubro: 9,
    novembro: 10,
    dezembro: 11,
    fev: 1,
    abr: 3,
    mai: 4,
    ago: 7,
    set: 8,
    out: 9,
    dez: 11,
  },
  units: {
    dia: "daily",
    dias: "daily",
    semana: "weekly",
    semanas: "weekly",
    mês: "monthly",
    meses: "monthly",
    ano: "yearly",
    anos: "yearly",
  },
  inPrefixes: ["em", "daqui a", "dentro de"],
  nextPrefixes: ["próximo", "próxima"],
  nextSuffixes: ["que vem"],
  thisPrefixes: ["este", "esta", "nesta", "neste"],
  leadIns: ["na", "no", "a", "o"],
  monthConnectors: ["de"],
  every: ["toda", "todo", "todas as", "todos os", "a cada", "cada"],
  single: {
    diariamente: "daily",
    semanalmente: "weekly",
    mensalmente: "monthly",
    anualmente: "yearly",
  },
  fromCompletion: ["após conclusão", "após a conclusão", "a partir da conclusão"],
  // "às" folds to the article "as" ("as 3 tarefas"), so a bare hour needs its "h": "às 17h".
  timePrefixes: { às: false },
  timeSuffixes: ["h"],
  hourLetter: "h",
  noon: ["meio-dia"],
  midnight: ["meia-noite"],
};

const EN: QuickAddLexicon = {
  monthFirst: true,
  one: ["a", "an", "one"],
  relativeDays: { today: 0, tonight: 0, tomorrow: 1, overmorrow: 2 },
  weekdays: {
    sunday: 0,
    monday: 1,
    tuesday: 2,
    wednesday: 3,
    thursday: 4,
    friday: 5,
    saturday: 6,
    sun: 0,
    mon: 1,
    tue: 2,
    wed: 3,
    thu: 4,
    fri: 5,
    sat: 6,
  },
  months: {
    january: 0,
    february: 1,
    march: 2,
    april: 3,
    may: 4,
    june: 5,
    july: 6,
    august: 7,
    september: 8,
    october: 9,
    november: 10,
    december: 11,
    jan: 0,
    feb: 1,
    mar: 2,
    apr: 3,
    jun: 5,
    jul: 6,
    aug: 7,
    sep: 8,
    sept: 8,
    oct: 9,
    nov: 10,
    dec: 11,
  },
  units: {
    day: "daily",
    days: "daily",
    week: "weekly",
    weeks: "weekly",
    month: "monthly",
    months: "monthly",
    year: "yearly",
    years: "yearly",
  },
  inPrefixes: ["in"],
  nextPrefixes: ["next"],
  nextSuffixes: [],
  thisPrefixes: ["this"],
  leadIns: ["on"],
  monthConnectors: ["of"],
  every: ["every"],
  single: { daily: "daily", weekly: "weekly", monthly: "monthly", yearly: "yearly" },
  fromCompletion: ["from completion"],
  // "at 5" stays text ("meet at 5 lakes"); "at 5pm" and "at 17:00" are times.
  timePrefixes: { at: false },
  timeSuffixes: [],
  noon: ["noon"],
  midnight: ["midnight"],
};

const DA: QuickAddLexicon = {
  monthFirst: true,
  one: ["en", "et"],
  relativeDays: {
    "i dag": 0,
    "i aften": 0,
    "i morgen": 1,
    overmorgen: 2,
    "i overmorgen": 2,
  },
  weekdays: {
    søndag: 0,
    mandag: 1,
    tirsdag: 2,
    onsdag: 3,
    torsdag: 4,
    fredag: 5,
    lørdag: 6,
    soendag: 0,
    loerdag: 6,
    søn: 0,
    man: 1,
    tir: 2,
    ons: 3,
    tor: 4,
    fre: 5,
    lør: 6,
    soen: 0,
    loer: 6,
  },
  months: {
    januar: 0,
    februar: 1,
    marts: 2,
    april: 3,
    maj: 4,
    juni: 5,
    juli: 6,
    august: 7,
    september: 8,
    oktober: 9,
    november: 10,
    december: 11,
    jan: 0,
    feb: 1,
    mar: 2,
    apr: 3,
    jun: 5,
    jul: 6,
    aug: 7,
    sep: 8,
    sept: 8,
    okt: 9,
    nov: 10,
    dec: 11,
  },
  units: {
    dag: "daily",
    dage: "daily",
    uge: "weekly",
    uger: "weekly",
    måned: "monthly",
    måneder: "monthly",
    maaned: "monthly",
    maaneder: "monthly",
    år: "yearly",
    aar: "yearly",
  },
  inPrefixes: ["om"],
  nextPrefixes: ["næste", "naeste"],
  nextSuffixes: [],
  thisPrefixes: ["denne", "dette"],
  leadIns: ["på", "paa", "den"],
  monthConnectors: [],
  every: ["hver", "hvert"],
  single: {
    dagligt: "daily",
    ugentligt: "weekly",
    månedligt: "monthly",
    maanedligt: "monthly",
    årligt: "yearly",
    aarligt: "yearly",
  },
  fromCompletion: ["fra fuldførelse", "fra fuldfoerelse", "fra fulfoerelse"],
  timePrefixes: { kl: true, "kl.": true },
  gluedTimePrefixes: ["kl.", "kl"],
  timeSuffixes: [],
  // No noon word: "middag" is also dinner ("lav middag").
  noon: [],
  midnight: ["midnat"],
};

const SOURCES: Record<string, QuickAddLexicon> = {
  en: EN,
  da: DA,
  de: DE,
  es: ES,
  fr: FR,
  it: IT,
  nl: NL,
  pl: PL,
  pt: PT,
};

/** A lexicon with every phrase passed through {@link fold}, so lookups are plain comparisons. */
function folded(lex: QuickAddLexicon): QuickAddLexicon {
  const keys = <T>(rec: Record<string, T>) =>
    Object.fromEntries(Object.entries(rec).map(([k, v]) => [fold(k), v])) as Record<string, T>;
  const list = (xs: string[]) => xs.map(fold);
  return {
    ...lex,
    one: list(lex.one),
    gluedTimePrefixes: list(lex.gluedTimePrefixes ?? []),
    relativeDays: keys(lex.relativeDays),
    weekdays: keys(lex.weekdays),
    months: keys(lex.months),
    units: keys(lex.units),
    inPrefixes: list(lex.inPrefixes),
    nextPrefixes: list(lex.nextPrefixes),
    nextSuffixes: list(lex.nextSuffixes),
    thisPrefixes: list(lex.thisPrefixes),
    leadIns: list(lex.leadIns),
    monthConnectors: list(lex.monthConnectors),
    every: list(lex.every),
    single: keys(lex.single),
    fromCompletion: list(lex.fromCompletion),
    timePrefixes: keys(lex.timePrefixes),
    timeSuffixes: list(lex.timeSuffixes),
    noon: list(lex.noon),
    midnight: list(lex.midnight),
  };
}

const LEXICONS: Record<string, QuickAddLexicon> = Object.fromEntries(
  Object.entries(SOURCES).map(([code, lex]) => [code, folded(lex)]),
);

/**
 * The (folded) lexicons to match for a UI language such as "de" or "pt-BR", in order: its own, then
 * English. English alone for English, no language, or one without a lexicon.
 */
export function quickAddLexicons(language: string | undefined): QuickAddLexicon[] {
  const base = (language ?? "").toLowerCase().split(/[-_]/)[0] ?? "";
  const own = LEXICONS[base];
  return own && base !== "en" ? [own, LEXICONS.en!] : [LEXICONS.en!];
}
